global:
  images:
    imageCredentials:
      registry: "registry.replicated.com/pharmasuite"
      username: "2pzTmDLObnWxAkfqZLsrCU3CnVe"
      password: "2pzTmDLObnWxAkfqZLsrCU3CnVe"
  enableIqTool:
    ftpc: true
    ftps: true
    ftei: true
replicated:
  enabled: true
micka:
  enabled: true
  flux2:
    cli:
      image: "registry.replicated.com/pharmasuite/flux-cli"
    sourceController:
      image: "registry.replicated.com/pharmasuite/source-controller"
    kustomizeController:
      image: "registry.replicated.com/pharmasuite/kustomize-controller"
  gitops-deployment:
    enabled: true
    gitRepository: &gitRepo
      interval: 1m0s
      url: "https://github.com/ysingh-rok/ps12-k8s-rok1"
      branch: main
      path: "FTPS12/custom" #updated path
      credentials:
        ca: |
          -----BEGIN CERTIFICATE-----
          MIICjzCCAhWgAwIBAgIQXIuZxVqUxdJxVt7NiYDMJjAKBggqhkjOPQQDAzCBiDEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCk5ldyBKZXJzZXkxFDASBgNVBAcTC0plcnNl
          eSBDaXR5MR4wHAYDVQQKExVUaGUgVVNFUlRSVVNUIE5ldHdvcmsxLjAsBgNVBAMT
          JVVTRVJUcnVzdCBFQ0MgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTAwMjAx
          MDAwMDAwWhcNMzgwMTE4MjM1OTU5WjCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgT
          Ck5ldyBKZXJzZXkxFDASBgNVBAcTC0plcnNleSBDaXR5MR4wHAYDVQQKExVUaGUg
          VVNFUlRSVVNUIE5ldHdvcmsxLjAsBgNVBAMTJVVTRVJUcnVzdCBFQ0MgQ2VydGlm
          aWNhdGlvbiBBdXRob3JpdHkwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAQarFRaqflo
          I+d61SRvU8Za2EurxtW20eZzca7dnNYMYf3boIkDuAUU7FfO7l0/4iGzzvfUinng
          o4N+LZfQYcTxmdwlkWOrfzCjtHDix6EznPO/LlxTsV+zfTJ/ijTjeXmjQjBAMB0G
          A1UdDgQWBBQ64QmG1M8ZwpZ2dEl23OA1xmNjmjAOBgNVHQ8BAf8EBAMCAQYwDwYD
          VR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAwNoADBlAjA2Z6EWCNzklwBBHU6+4WMB
          zzuqQhFkoJ2UOQIReVx7Hfpkue4WQrO/isIJxOzksU0CMQDpKmFHjFJKS04YcPbW
          RNZu9YO6bVi9JNlWSOrvxKJGgYhqOkbRqZtNyWHa0V1Xahg=
          -----END CERTIFICATE-----
        username: ysingh-rok
        email: "yogendra.singh@rockwellautomation.com"
        password: "ghp_eheQACjZK9qwrPzvQGcFeMCRFkziOd0YYjef"
    sops:
      ageKey: "AGE-SECRET-KEY-1054ERQLAMD6VCKVER0E0HE78HJD50TXVCDPMS2U0G0Z0MMUNDMRS4SAS6G"
  sample-configuration:
    enabled: true
    gitRepository: *gitRepo
    sampleConfiguration:
      chartSourceAuthUsername: "2pzTmDLObnWxAkfqZLsrCU3CnVe"
      chartSourceAuthPassword: "2pzTmDLObnWxAkfqZLsrCU3CnVe"
      converterTool:
        config:
          converter:
            chartSource: "oci://registry.replicated.com/pharmasuite/pharmasuite-12-community-of-practice"
ftpc-micka-post-deployment-config:
  enabled: true
ftps-micka-post-deployment-config:
  enabled: true
ftei-micka-post-deployment-config:
  enabled: true
observability-micka-post-deployment-config:
  enabled: true
