apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../dev/deployments/secrets/site1-dev-ftps-solution-deployment-secrets.yaml
  - ../dev/post-deployment/flux-kustomization.yaml
