apiVersion: v1
kind: Secret
metadata:
  name: site1-dev-ftps-solution-deployment-secrets
type: Opaque
stringData:
  kubeconfig: ""
  global.components.db.active.username: ""
  global.components.db.active.password: ""
